name: Run Raspberry Pi Scripts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          # Asegúrate de que las rutas de los scripts sean correctas
          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaperarmhf.sh
          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaper_Buster_Bullseye_64bit.sh 
          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaper_bookworm.sh

      - name: Run Bookworm 32-bit Script
        id: bookworm_32
        run: |
          echo "Running Bookworm 32-bit Script"
          qemu-arm-static ${GITHUB_WORKSPACE}/rpibsas_reaperarmhf.sh > bookworm_32_output.txt 2>&1 || true
          echo "Versions and errors for Bookworm 32-bit" > results_armhf.txt
          echo "-----" >> results_armhf.txt
          cat bookworm_32_output.txt >> results_armhf.txt

      - name: Run Bullseye 64-bit Script
        id: bullseye_64
        run: |
          echo "Running Bullseye 64-bit Script"
          qemu-aarch64-static ${GITHUB_WORKSPACE}/rpibsas_reaper_Buster_Bullseye_64bit.sh > rpibsas_reaper_Buster_Bullseye_64bit_output.txt 2>&1 || true
          echo "Versions and errors for Buster and Bullseye 64-bit" >> results_bullseye_64.txt
          echo "-----" >> results_bullseye_64.txt
          cat rpibsas_reaper_Buster_Bullseye_64bit_output.txt >> results_bullseye_64.txt

      - name: Run Bookworm 64-bit Script
        id: bookworm_64
        run: |
          echo "Running Bookworm 64-bit Script"
          qemu-aarch64-static ${GITHUB_WORKSPACE}/rpibsas_reaper_bookworm.sh > rpibsas_reaper_bookworm_output.txt 2>&1 || true
          echo "Versions and errors for Bookworm 64-bit" >> results_bookworm.txt
          echo "-----" >> results_bookworm.txt
          cat rpibsas_reaper_bookworm_output.txt >> results_bookworm.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}  # Usa el tag que activó el flujo de trabajo
          files: ./*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
